spring.application.name=datasource-routing-app
server.port=9191
### MASTER_DB_CONFIGURATION
spring.datasource.master.url=jdbc:postgresql://localhost:6000/customer_master_db
spring.datasource.master.username=master
spring.datasource.master.password=master1234
spring.datasource.master.driver-class-name=org.postgresql.Driver
### REPLICA_DB_CONFIGURATION
spring.datasource.replica.url=jdbc:postgresql://localhost:6001/customer_master_db
spring.datasource.replica.username=master
spring.datasource.replica.password=master1234
spring.datasource.replica.driver-class-name=org.postgresql.Driver
### HIBERNATE SETTINGS
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.default_schema=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

### FLYWAY CONFIGURATION
spring.flyway.enabled=false
#spring.flyway.url=jdbc:postgresql://localhost:6000/customer_master_db
#spring.flyway.user=master
#spring.flyway.password=master1234
#spring.flyway.schemas=app_live
#spring.flyway.default-schema=app_live
##spring.flyway.validate-on-migrate=true
#spring.flyway.locations=classpath:db/migration

spring.jpa.open-in-view=false

#
# LOG LEVEL
#logging.pattern.level= "%5p [${spring.application.name}: correlationId:%X{correlationId} , token-id:%X{token} ]"
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=TRACE
logging.level.com.zaxxer.hikari=TRACE
logging.level.tr.otunctan.dsr=DEBUG
